// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/*
 *Name:
 *Date: 12/14/2022
 *Description: In firebase_options.dart,...
 *Bugs: N/A
 *Reflection: N/A
*/

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0lPM_o_XBtzcONsD-UsipfvxVP2wqx1Q',
    appId: '1:1023081956705:web:f9ba14d7c893ed800b7120',
    messagingSenderId: '1023081956705',
    projectId: 'getgroovy-a42ac',
    authDomain: 'getgroovy-a42ac.firebaseapp.com',
    storageBucket: 'getgroovy-a42ac.appspot.com',
    measurementId: 'G-60TDZFF100',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM1LGj-wD-1sxOu4g2Cf1ADvNFalXyX2A',
    appId: '1:1023081956705:android:d7b0cec8b3ea6c390b7120',
    messagingSenderId: '1023081956705',
    projectId: 'getgroovy-a42ac',
    storageBucket: 'getgroovy-a42ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnLagvXQ5r-U30lDNgcs5lun9oIql-ELQ',
    appId: '1:1023081956705:ios:05a826b709ea04df0b7120',
    messagingSenderId: '1023081956705',
    projectId: 'getgroovy-a42ac',
    storageBucket: 'getgroovy-a42ac.appspot.com',
    iosClientId: '1023081956705-5hmnjfrdkoqcsn2ncpvehn3mg2kin0u1.apps.googleusercontent.com',
    iosBundleId: 'com.example.getgroovy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnLagvXQ5r-U30lDNgcs5lun9oIql-ELQ',
    appId: '1:1023081956705:ios:05a826b709ea04df0b7120',
    messagingSenderId: '1023081956705',
    projectId: 'getgroovy-a42ac',
    storageBucket: 'getgroovy-a42ac.appspot.com',
    iosClientId: '1023081956705-5hmnjfrdkoqcsn2ncpvehn3mg2kin0u1.apps.googleusercontent.com',
    iosBundleId: 'com.example.getgroovy',
  );
}
